name: SpotBugs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file Operations/pom.xml 
    - name: Spot with Maven
      run: mvn verify spotbugs:spotbugs
    - uses: jwgmeligmeyling/spotbugs-github-action@master
      with:
        path: '**Operations/spotbugsXml.xml'
