name: lint

on:
  push:
    branches: [ main ]

jobs:
  lint-code:
    runs-on: ubuntu-20.04
    steps:
    - name: Lint Code
      uses: github/super-linter@v3
      env: |
        VALIDATE_ALL_CODEBASE:false
        DEFAULT_BRANCH:main
        GITHUB_TOKEN:${{secrets.GITHUB_TOKEN}}
