name: Calculator Test
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        run: echo searching code...
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
    
      - name: Display structure of downloaded files
        run: ls -R
